version: "3"

services:
  auth_mc:
    build: .
    container_name: auth_mc
    depends_on:
      - db
    restart: always
    environment:
      - CONFIG_PATH=./config/dev.yaml
    ports:
      - "8002:44044"

  db:
    image: postgres
    container_name: db
    volumes:
      - ./database/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "auth"
    ports:
      - "5432:5432"

