env: "dev"
storage_path:
    POSTGRES_PASSWORD: "123456"
    POSTGRES_HOST: "localhost"
    POSTGRES_USER: "postgre"
    POSTGRES_DB: "postgre"
dev_storage: "./test.db"
grpc:
  port: 44044
  timeout: 1h
secret: "dasdasdd"

  